export const SAMPLE_LOGS_DATA = [
  "GET /api/user 200",
  "POST /api/login 401",
  "PUT /api/profile 204",
  "DELETE /api/session 200",
  "DB query executed in 42ms",
  "Prisma transaction committed",
  "Redis connected",
  "Redis cache miss: user-feed",
  "Cache hit: user-profile",
  "Worker processed job #42",
  "Worker retrying failed task",
  "Auth token verified",
  "JWT expired for user #182",
  "Stripe webhook received",
  "Webhook signature validated",
  "Email queued successfully",
  "BullMQ queue drained",
  "WebSocket client connected",
  "WebSocket reconnecting...",
  "Memory usage at 78%",
  "CPU spike detected",
  "Server started on port 3000",
  "Rate limit exceeded for IP",
  "S3 upload completed",
  "Background sync finished",
  "Cron job executed",
  "Feature flag enabled: beta-ui",
  "Kafka event published",
  "Kafka consumer lag detected",
  "Request completed in 123ms",
  "Request timeout after 5s",
  "New deployment triggered",
  "Healthcheck passed",
  "Error: Cannot read property 'id'",
  "Unhandled promise rejection",
  "Session refreshed successfully",
  "Connected to PostgreSQL",
  "Database replication healthy",
  "Image optimization completed",
  "CDN cache purged",
];
